In [1]:
from logger import logger
import numpy as np
from dumpers import SCV_Dumper
from multiprocessing import Queue, Process


class Test1:
    @logger.log(headers=["fun_name", "output", "args"])
    def foo(self, a, b):
        return a + b

    @logger.log()
    def boo(self):
        return (list([1, 23, 4]), np.array([1, 2, 3]))


class Test2:
    @logger.log()
    def freez(self, a=np.array([1, 234, 4]), b=4):
        d = {
            "a": np.arange(0, 10),
            "b": [1, 2, 34],
            "c": self,
        }
        return d

    @logger.log()
    def brah(self, c):
        d = {
            "a": np.arange(0, 10),
            "b": [1, 2, 34],
            "c": self,
        }
        return d, list([1, 23, 4]), np.array([1, 2, 3])

In [2]:
dumper = SCV_Dumper(logger)

In [3]:
test1 = Test1()
test2 = Test2()

In [4]:
dupmer = Process(target=dumper.dump_loop)
dupmer.start()

In [5]:
def experiments1():
    for i in range(4):
        test1.foo(i, i**2)
        test1.boo()
        test2.freez()


def experiments2():
    for _ in range(8):
        test2.brah(None)


Process(target=experiments1).start()
Process(target=experiments2).start()

In [6]:
dupmer.terminate()
logger.get_logger_performance()

 max logger time consumption 0.0013000965118408203 [s]
 mean logger time consumption 0.00022573471069335936 [s]
 total num calls 20.0

In [7]:
import pandas as pd
from os import walk

filenames = next(walk("./logs/"), (None, None, []))[2]

In [8]:
filenames[0]

'logs_29_12_2023_13:45:19.csv'

In [9]:
data = pd.read_csv(f"./logs/{filenames[0]}", sep="|").replace("_", None)
data

,fun_name,call_time,exec_time,output,args,kwargs
0,foo,None,None,0,"[""<class '__main__.Test1'>"", 0, 0]",None
1,boo,1703846720.774116,0.0001480579376220703,"[[1, 23, 4], [1, 2, 3]]","[""<class '__main__.Test1'>""]",{}
2,freez,1703846720.7748055,0.0001766681671142578,[ 5 238 8],"[""<class '__main__.Test2'>""]",{}
3,foo,None,None,2,"[""<class '__main__.Test1'>"", 1, 1]",None
4,boo,1703846720.775659,1.049041748046875e-05,"[[1, 23, 4], [1, 2, 3]]","[""<class '__main__.Test1'>""]",{}
5,freez,1703846720.7758334,1.7881393432617188e-05,[ 5 238 8],"[""<class '__main__.Test2'>""]",{}
6,foo,None,None,6,"[""<class '__main__.Test1'>"", 2, 4]",None
7,boo,1703846720.7758834,2.1219253540039062e-05,"[[1, 23, 4], [1, 2, 3]]","[""<class '__main__.Test1'>""]",{}
8,freez,1703846720.775945,4.5299530029296875e-06,[ 5 238 8],"[""<class '__main__.Test2'>""]",{}
9,foo,None,None,12,"[""<class '__main__.Test1'>"", 3, 9]",None
10,boo,1703846720.775983,1.9311904907226562e-05,"[[1, 23, 4], [1, 2, 3]]","[""<class '__main__.Test1'>""]",{}
11,freez,1703846720.7760158,3.337860107421875e-06,[ 5 238 8],"[""<class '__main__.Test2'>""]",{}
12,brah,1703846720.780633,0.00011682510375976562,"[{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), ...","[""<class '__main__.Test2'>"", ""<class 'NoneType...",{}
13,brah,1703846720.7813447,3.9577484130859375e-05,"[{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), ...","[""<class '__main__.Test2'>"", ""<class 'NoneType...",{}
14,brah,1703846720.7821255,1.1682510375976562e-05,"[{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), ...","[""<class '__main__.Test2'>"", ""<class 'NoneType...",{}
15,brah,1703846720.782397,1.0967254638671875e-05,"[{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), ...","[""<class '__main__.Test2'>"", ""<class 'NoneType...",{}
16,brah,1703846720.78273,1.1682510375976562e-05,"[{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), ...","[""<class '__main__.Test2'>"", ""<class 'NoneType...",{}
17,brah,1703846720.7829704,3.0517578125e-05,"[{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), ...","[""<class '__main__.Test2'>"", ""<class 'NoneType...",{}
18,brah,1703846720.7832642,3.0040740966796875e-05,"[{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), ...","[""<class '__main__.Test2'>"", ""<class 'NoneType...",{}
19,brah,1703846720.783596,4.315376281738281e-05,"[{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), ...","[""<class '__main__.Test2'>"", ""<class 'NoneType...",{}

In [10]:
boo_data = data[data["fun_name"] == "foo"]
boo_data

,fun_name,call_time,exec_time,output,args,kwargs
0,foo,None,None,0,"[""<class '__main__.Test1'>"", 0, 0]",None
3,foo,None,None,2,"[""<class '__main__.Test1'>"", 1, 1]",None
6,foo,None,None,6,"[""<class '__main__.Test1'>"", 2, 4]",None
9,foo,None,None,12,"[""<class '__main__.Test1'>"", 3, 9]",None